// Mock product categories
export const categories = [
  'All Products',
  'Surgical Supplies',
  'Diagnostic Equipment',
  'Personal Protection',
  'Laboratory',
  'Patient Care',
  'Emergency Medical',
];

// Mock suppliers
export const mockSuppliers = [
  {
    id: 'SUP-001',
    name: 'MedTech Solutions',
    email: 'supplier@medtech.com',
    status: 'active',
    commissionRate: 15,
    totalProducts: 5,
    totalSales: 12450.50,
    pendingPayout: 1867.58,
    registeredDate: '2024-01-10',
    businessInfo: {
      address: '456 Medical Park, Boston, MA 02118',
      phone: '(555) 123-4567',
      taxId: 'EIN-12-3456789',
      bankAccount: '****1234',
    }
  },
  {
    id: 'SUP-002',
    name: 'SafeGuard Medical',
    email: 'supplier@safeguard.com',
    status: 'active',
    commissionRate: 12,
    totalProducts: 3,
    totalSales: 8920.75,
    pendingPayout: 1070.49,
    registeredDate: '2024-01-15',
    businessInfo: {
      address: '789 Health Plaza, Cambridge, MA 02139',
      phone: '(555) 234-5678',
      taxId: 'EIN-98-7654321',
      bankAccount: '****5678',
    }
  },
  {
    id: 'SUP-003',
    name: 'CardioCare Pro',
    email: 'supplier@cardiocare.com',
    status: 'active',
    commissionRate: 15,
    totalProducts: 1,
    totalSales: 4799.70,
    pendingPayout: 719.96,
    registeredDate: '2024-01-12',
    businessInfo: {
      address: '321 Cardiac Way, Newton, MA 02458',
      phone: '(555) 345-6789',
      taxId: 'EIN-11-2233445',
      bankAccount: '****9012',
    }
  },
];

// Mock pending suppliers (legacy - kept for backward compat)
export const mockPendingSuppliers = [
  {
    id: 'PEND-001',
    name: 'Global Medical Supplies Inc.',
    email: 'contact@globalmedical.com',
    company: 'Global Medical Supplies Inc.',
    status: 'pending',
    registeredDate: '2024-01-25',
    businessInfo: {
      address: '555 Commerce St, Boston, MA 02110',
      phone: '(555) 456-7890',
      taxId: 'EIN-44-5566778',
      website: 'www.globalmedical.com',
    }
  },
];

// Mock vendors (approved suppliers who can sell)
export const mockVendors = [
  {
    id: 'VEN-001',
    name: 'MedTech Solutions',
    contactName: 'Robert Chen',
    email: 'supplier@medtech.com',
    company: 'MedTech Solutions',
    status: 'approved',
    commissionRate: 15,
    totalProducts: 5,
    totalSales: 12450.50,
    pendingPayout: 1867.58,
    registeredDate: '2024-01-10',
    approvedDate: '2024-01-12',
    categories: ['Diagnostic Equipment', 'Patient Care', 'Emergency Medical'],
    businessInfo: {
      address: '456 Medical Park, Boston, MA 02118',
      phone: '(555) 123-4567',
      taxId: 'EIN-12-3456789',
      website: 'www.medtechsolutions.com',
      yearsInBusiness: 8,
    },
  },
  {
    id: 'VEN-002',
    name: 'SafeGuard Medical',
    contactName: 'Lisa Nguyen',
    email: 'supplier@safeguard.com',
    company: 'SafeGuard Medical',
    status: 'approved',
    commissionRate: 12,
    totalProducts: 3,
    totalSales: 8920.75,
    pendingPayout: 1070.49,
    registeredDate: '2024-01-15',
    approvedDate: '2024-01-17',
    categories: ['Personal Protection', 'Laboratory', 'Surgical Supplies'],
    businessInfo: {
      address: '789 Health Plaza, Cambridge, MA 02139',
      phone: '(555) 234-5678',
      taxId: 'EIN-98-7654321',
      website: 'www.safeguardmedical.com',
      yearsInBusiness: 5,
    },
  },
  {
    id: 'VEN-003',
    name: 'CardioCare Pro',
    contactName: 'Daniel Wu',
    email: 'supplier@cardiocare.com',
    company: 'CardioCare Pro',
    status: 'approved',
    commissionRate: 15,
    totalProducts: 1,
    totalSales: 4799.70,
    pendingPayout: 719.96,
    registeredDate: '2024-01-12',
    approvedDate: '2024-01-14',
    categories: ['Diagnostic Equipment'],
    businessInfo: {
      address: '321 Cardiac Way, Newton, MA 02458',
      phone: '(555) 345-6789',
      taxId: 'EIN-11-2233445',
      website: 'www.cardioprocare.com',
      yearsInBusiness: 12,
    },
  },
];

// Mock pending vendor applications
export const mockPendingVendors = [
  {
    id: 'VAPP-001',
    name: 'Global Medical Supplies Inc.',
    contactName: 'Marcus Thompson',
    email: 'contact@globalmedical.com',
    company: 'Global Medical Supplies Inc.',
    status: 'pending',
    registeredDate: '2024-01-25',
    categories: ['Surgical Supplies', 'Emergency Medical'],
    businessInfo: {
      address: '555 Commerce St, Boston, MA 02110',
      phone: '(555) 456-7890',
      taxId: 'EIN-44-5566778',
      website: 'www.globalmedical.com',
      yearsInBusiness: 3,
    },
  },
  {
    id: 'VAPP-002',
    name: 'BioHealth Distributors',
    contactName: 'Priya Kapoor',
    email: 'priya@biohealthdist.com',
    company: 'BioHealth Distributors',
    status: 'pending',
    registeredDate: '2024-01-27',
    categories: ['Laboratory', 'Diagnostic Equipment'],
    businessInfo: {
      address: '112 Science Blvd, Worcester, MA 01609',
      phone: '(555) 567-8901',
      taxId: 'EIN-77-8899001',
      website: 'www.biohealthdist.com',
      yearsInBusiness: 6,
    },
  },
  {
    id: 'VAPP-003',
    name: 'QuickMed Supplies LLC',
    contactName: 'James Foster',
    email: 'james@quickmed.io',
    company: 'QuickMed Supplies LLC',
    status: 'rejected',
    registeredDate: '2024-01-20',
    rejectedDate: '2024-01-22',
    rejectionReason: 'Incomplete documentation — Tax ID could not be verified.',
    categories: ['Personal Protection'],
    businessInfo: {
      address: '78 Industrial Ave, Springfield, MA 01103',
      phone: '(555) 678-9012',
      taxId: 'EIN-00-0000000',
      website: '',
      yearsInBusiness: 1,
    },
  },
];

// Mock products data with supplier information
export const mockProducts = [
  {
    id: '1',
    name: 'Digital Blood Pressure Monitor',
    category: 'Diagnostic Equipment',
    price: 89.99,
    stock: 45,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Professional-grade automatic blood pressure monitor with large LCD display and irregular heartbeat detection.',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=500',
    features: ['Automatic inflation', 'Memory for 2 users', 'Irregular heartbeat indicator', 'Large LCD display'],
    specifications: {
      accuracy: '±3 mmHg',
      measurementRange: '0-299 mmHg',
      pulseRange: '40-199 bpm',
      warranty: '2 years',
    },
  },
  {
    id: '2',
    name: 'Surgical Gloves - Latex Free (Box of 100)',
    category: 'Personal Protection',
    price: 24.99,
    stock: 200,
    supplierId: 'SUP-002',
    supplier: 'SafeGuard Medical',
    description: 'Powder-free nitrile examination gloves, latex-free for sensitive users.',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=500',
    features: ['Latex-free', 'Powder-free', 'Textured fingertips', 'Ambidextrous'],
    specifications: {
      material: 'Nitrile',
      thickness: '4.7 mil',
      size: 'Medium',
      certification: 'FDA approved',
    },
  },
  {
    id: '3',
    name: 'Stethoscope - Professional Cardiology',
    category: 'Diagnostic Equipment',
    price: 159.99,
    stock: 30,
    supplierId: 'SUP-003',
    supplier: 'CardioCare Pro',
    description: 'High-quality cardiology stethoscope with superior acoustic performance.',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500',
    features: ['Dual head design', 'Superior acoustics', 'Soft-sealing ear tips', 'Latex-free tubing'],
    specifications: {
      chestpiece: 'Dual sided',
      tubing: '27 inches',
      weight: '185g',
      warranty: '5 years',
    },
  },
  {
    id: '4',
    name: 'Wheelchair - Foldable Transport',
    category: 'Patient Care',
    price: 299.99,
    stock: 15,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Lightweight aluminum wheelchair with padded armrests and adjustable footrests.',
    image: 'https://images.unsplash.com/photo-1582719366037-2c4d7c1a0413?w=500',
    features: ['Lightweight aluminum frame', 'Foldable design', 'Padded armrests', 'Adjustable footrests'],
    specifications: {
      weight: '32 lbs',
      capacity: '300 lbs',
      seatWidth: '18 inches',
      warranty: '1 year',
    },
  },
  {
    id: '5',
    name: 'Pulse Oximeter - Fingertip',
    category: 'Diagnostic Equipment',
    price: 34.99,
    stock: 150,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Accurate fingertip pulse oximeter for SpO2 and pulse rate monitoring.',
    image: 'https://images.unsplash.com/photo-1615461066159-fea0960485d5?w=500',
    features: ['OLED display', 'Auto power-off', 'Low battery indicator', 'Portable with lanyard'],
    specifications: {
      spO2Range: '70%-100%',
      pulseRange: '30-250 bpm',
      accuracy: '±2%',
      batteryLife: '30 hours',
    },
  },
  {
    id: '6',
    name: 'Surgical Face Masks (Box of 50)',
    category: 'Personal Protection',
    price: 19.99,
    stock: 300,
    supplierId: 'SUP-002',
    supplier: 'SafeGuard Medical',
    description: '3-ply disposable surgical face masks with earloops.',
    image: 'https://images.unsplash.com/photo-1584634428767-8fe0e7022242?w=500',
    features: ['3-ply protection', 'Comfortable earloops', 'Adjustable nose bridge', 'Breathable material'],
    specifications: {
      bfe: '>95%',
      pfe: '>95%',
      fluidResistance: '120 mmHg',
      certification: 'ASTM Level 2',
    },
  },
  {
    id: '7',
    name: 'Infrared Thermometer - Non-Contact',
    category: 'Diagnostic Equipment',
    price: 45.99,
    stock: 80,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Fast and accurate non-contact infrared thermometer with fever alarm.',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500',
    features: ['Non-contact measurement', 'Fever alarm', 'Memory recall', 'Backlit display'],
    specifications: {
      range: '89.6°F - 109.2°F',
      accuracy: '±0.4°F',
      distance: '2-3 inches',
      responseTime: '1 second',
    },
  },
  {
    id: '8',
    name: 'Medical Grade Disinfectant Spray',
    category: 'Laboratory',
    price: 12.99,
    stock: 250,
    supplierId: 'SUP-002',
    supplier: 'SafeGuard Medical',
    description: 'Hospital-grade disinfectant effective against viruses and bacteria.',
    image: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=500',
    features: ['99.9% kill rate', 'Fast-acting', 'No-rinse formula', 'Pleasant scent'],
    specifications: {
      volume: '32 oz',
      activeIngredient: 'Quaternary ammonium',
      contactTime: '30 seconds',
      certification: 'EPA registered',
    },
  },
  {
    id: '9',
    name: 'Emergency First Aid Kit - Professional',
    category: 'Emergency Medical',
    price: 79.99,
    stock: 50,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Comprehensive first aid kit with 200+ pieces for emergencies.',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=500',
    features: ['200+ pieces', 'Waterproof case', 'Organized compartments', 'OSHA compliant'],
    specifications: {
      dimensions: '12x9x4 inches',
      weight: '3.5 lbs',
      capacity: '25 people',
      certification: 'OSHA/ANSI',
    },
  },
  {
    id: '10',
    name: 'IV Administration Set',
    category: 'Surgical Supplies',
    price: 8.99,
    stock: 500,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Sterile IV administration set with precision flow control.',
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=500',
    features: ['Sterile single-use', 'Precision roller clamp', 'Luer lock', 'Air-eliminating filter'],
    specifications: {
      dropFactor: '20 drops/mL',
      tubingLength: '72 inches',
      sterilization: 'ETO',
      shelf: '5 years',
    },
  },
  {
    id: '11',
    name: 'Digital Glucose Meter Kit',
    category: 'Diagnostic Equipment',
    price: 54.99,
    stock: 65,
    supplierId: 'SUP-001',
    supplier: 'MedTech Solutions',
    description: 'Complete blood glucose monitoring system with 50 test strips.',
    image: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=500',
    features: ['Fast 5-second results', '50 test strips included', 'Large display', 'Data memory'],
    specifications: {
      range: '20-600 mg/dL',
      sampleSize: '0.5 µL',
      testTime: '5 seconds',
      memory: '500 readings',
    },
  },
  {
    id: '12',
    name: 'Disposable Syringes 10mL (Box of 100)',
    category: 'Surgical Supplies',
    price: 29.99,
    stock: 180,
    supplierId: 'SUP-002',
    supplier: 'SafeGuard Medical',
    description: 'Sterile single-use syringes with Luer lock tip.',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500',
    features: ['Sterile single-use', 'Luer lock tip', 'Clear barrel', 'Bold scale markings'],
    specifications: {
      volume: '10 mL',
      material: 'Medical-grade polypropylene',
      sterilization: 'ETO',
      certification: 'FDA 510(k)',
    },
  },
];

// Mock orders for order history with supplier splits
export const mockOrders = [
  {
    id: 'ORD-2024-001',
    date: '2024-01-15',
    status: 'delivered',
    total: 324.97,
    items: [
      { 
        id: '1',
        name: 'Digital Blood Pressure Monitor', 
        quantity: 2, 
        price: 89.99,
        supplierId: 'SUP-001',
        supplier: 'MedTech Solutions',
      },
      { 
        id: '5',
        name: 'Pulse Oximeter - Fingertip', 
        quantity: 4, 
        price: 34.99,
        supplierId: 'SUP-001',
        supplier: 'MedTech Solutions',
      },
    ],
    // Order automatically split by supplier
    supplierOrders: [
      {
        supplierId: 'SUP-001',
        supplierName: 'MedTech Solutions',
        items: [
          { name: 'Digital Blood Pressure Monitor', quantity: 2, price: 89.99 },
          { name: 'Pulse Oximeter - Fingertip', quantity: 4, price: 34.99 },
        ],
        subtotal: 319.94,
        commission: 47.99, // 15% commission
        supplierPayout: 271.95,
        status: 'delivered',
      }
    ],
    shippingAddress: {
      name: 'John Smith',
      company: 'City Hospital',
      street: '123 Medical Center Dr',
      city: 'Boston',
      state: 'MA',
      zip: '02115',
    },
  },
  {
    id: 'ORD-2024-002',
    date: '2024-01-20',
    status: 'in_transit',
    total: 209.97,
    items: [
      { 
        id: '3',
        name: 'Stethoscope - Professional Cardiology', 
        quantity: 1, 
        price: 159.99,
        supplierId: 'SUP-003',
        supplier: 'CardioCare Pro',
      },
      { 
        id: '2',
        name: 'Surgical Gloves - Latex Free (Box of 100)', 
        quantity: 2, 
        price: 24.99,
        supplierId: 'SUP-002',
        supplier: 'SafeGuard Medical',
      },
    ],
    // Multi-supplier order - automatically split
    supplierOrders: [
      {
        supplierId: 'SUP-003',
        supplierName: 'CardioCare Pro',
        items: [
          { name: 'Stethoscope - Professional Cardiology', quantity: 1, price: 159.99 },
        ],
        subtotal: 159.99,
        commission: 24.00, // 15% commission
        supplierPayout: 135.99,
        status: 'in_transit',
      },
      {
        supplierId: 'SUP-002',
        supplierName: 'SafeGuard Medical',
        items: [
          { name: 'Surgical Gloves - Latex Free (Box of 100)', quantity: 2, price: 24.99 },
        ],
        subtotal: 49.98,
        commission: 6.00, // 12% commission
        supplierPayout: 43.98,
        status: 'in_transit',
      },
    ],
    shippingAddress: {
      name: 'John Smith',
      company: 'City Hospital',
      street: '123 Medical Center Dr',
      city: 'Boston',
      state: 'MA',
      zip: '02115',
    },
  },
];

// Mock pending users for admin
export const mockPendingUsers = [
  {
    id: 'pending-1',
    name: 'Sarah Johnson',
    email: 'sarah@clinic.com',
    company: 'Johnson Family Clinic',
    registeredDate: '2024-01-22',
    status: 'pending',
  },
  {
    id: 'pending-2',
    name: 'Michael Brown',
    email: 'mbrown@pharmacy.com',
    company: 'Brown\'s Pharmacy',
    registeredDate: '2024-01-23',
    status: 'pending',
  },
];
